l_japanese:
 EDITOR_SETTINGS: "編集設定"
 PERFORMANCE: "パフォーマンス"
 SPACE: "スペース"
 SPACES: "スペース"
 TAB: "タブ"
 TABS: "タブ"
 EXTERNAL_EDITOR: "外部エディター"
 EXTERNAL_EDITOR_DESC: "編集ボタンをクリックしたときに使用される外部エディターです。"
 SELECT_PROGRAM: "編集プログラムの選択"
 INDENTATION: "インデント"
 INDENTATION_DESC: "外部エディタやプレビューツールチップを使用する際に使用されるインデント文字です。"
 PAGE_SIZE: "ページサイズ"
 PAGE_SIZE_DESC: "1ページあたりに表示されるノードの量です。\n表示するノード数が多いほど、新しいノードを読み込むのに時間がかかります。"
 MAX_TOOLTIP_LINES: "ツールチップの最大行数"
 MAX_TOOLTIP_LINES_DESC: "ノードプレビューツールチップの最大行数。"
 ENABLE_NODE_TAGS: "ノードタグを有効にする"
 ENABLE_NODE_TAGS_DESC: "ノードタグは、表示するノードタグを決定するために、すべてのノードを分析する必要があるため、パフォーマンスが低下します。"
 ENABLE_NODE_JUMPS: "ノードジャンプを有効にする"
 ENABLE_NODE_JUMPS_DESC: "ノードジャンプは、すべてのノードを解析してジャンプ先を決定する必要があるため、性能が低下します。"
 WARN_ON_TYPE_CHANGE: "タイプ変更時の警告"
 WARN_ON_TYPE_CHANGE_DESC: "エントリーのデータ型を変更する場合、通常は意図していないため、警告を表示するようにしました。"
 EXTERNAL_EDITOR_WAIT_INTERVAL: "外部エディタ再読み込み待ち時間(ms)"
 EXTERNAL_EDITOR_WAIT_INTERVAL_DESC: "外部エディタで編集したファイルを保存する際、Pdx-Unlimiterエディタはファイルを読み込むまで指定された時間だけ待ちます。これは、低速のハードディスクを使用している場合に、早すぎる読み出しによるエラーを防ぐために有効です。"