l_french:
  EDITOR_SETTINGS: "Paramètres de l'éditeur"
  PERFORMANCE: "Performance"
  SPACE: "espace"
  SPACES: "espaces"
  TAB: "tabulation"
  TABS: "tabulations"
  EXTERNAL_EDITOR: "Éditeur externe "
  EXTERNAL_EDITOR_DESC: "L'éditeur externe utilisé lors de l'appui sur le bouton éditer."
  SELECT_PROGRAM: "Choisir un logiciel d'édition"
  INDENTATION: "Indentation "
  INDENTATION_DESC: "Charactère d'indentation utilisé par l'éditeur externe et les aperçus."
  PAGE_SIZE: "Taille de la page "
  PAGE_SIZE_DESC: "Le nombre de nœuds affichés par page.\nPlus ce nombre est grand, plus cela prend de temps à en charger plus."
  MAX_TOOLTIP_LINES: "Nombres de lignes des aperçus "
  MAX_TOOLTIP_LINES_DESC: "Le nombre macimum de lignes des aperçus des nœuds."
  ENABLE_NODE_TAGS: "Activer les balises de nœuds "
  ENABLE_NODE_TAGS_DESC: "Les balises de nœuds peuvent réduire les performances car chaque nœud doit être analysé."
  ENABLE_NODE_JUMPS: "Activer le saut de nœuds "
  ENABLE_NODE_JUMPS_DESC: "Le saut de nœuds peut réduire les performances car chaque nœud doit être analysé."
  WARN_ON_TYPE_CHANGE: "Avertir des changements de type "
  WARN_ON_TYPE_CHANGE_DESC: "Afficher un avertissement lorsque le type d'un nœud change, ce qui s'avère souvent une erreur."