l_english:
  EDITOR_SETTINGS: "Editor settings"
  PERFORMANCE: "Performance"
  SPACE: "space"
  SPACES: "spaces"
  TAB: "tab"
  TABS: "tabs"
  EXTERNAL_EDITOR: "External editor"
  EXTERNAL_EDITOR_DESC: "The external editor that will be used when clicking the edit button."
  SELECT_PROGRAM: "Select editor program"
  INDENTATION: "Indentation"
  INDENTATION_DESC: "Indentation characters that will be used when using the external editor and preview tooltips."
  PAGE_SIZE: "Page size"
  PAGE_SIZE_DESC: "The amount of nodes that are shown per page.\nThe more nodes are shown, the longer it takes to load new nodes."
  MAX_TOOLTIP_LINES: "Max tooltip lines"
  MAX_TOOLTIP_LINES_DESC: "The maximum lines of node preview tooltips."
  ENABLE_NODE_TAGS: "Enable node tags"
  ENABLE_NODE_TAGS_DESC: "Node tags decrease the performance since every node has to be analyzed to determine a node tag to show."
  ENABLE_NODE_JUMPS: "Enable node jumps"
  ENABLE_NODE_JUMPS_DESC: "Node jumps decrease the performance since every node has to be analyzed to determine where to jump."
  WARN_ON_TYPE_CHANGE: "Warn on type change"
  WARN_ON_TYPE_CHANGE_DESC: "Display a warning when changing the data type of an entry, since this is usually not intended."
  EXTERNAL_EDITOR_WAIT_INTERVAL: "External editor reload waiting period (ms)"
  EXTERNAL_EDITOR_WAIT_INTERVAL_DESC: "When saving an edited file using an external editor, the Pdx-Unlimiter editor waits the specified amount of time until reading the file. This can be useful to prevent errors caused by reading the file too early in case you are using a slow hard drive."