l_english:
 SETTINGS: "Settings"
 INTERFACE: "Interface"
 GENERAL: "General"
 IMPORTS: "Imports"
 IRONY: "Irony mod manager"
 USE_GAME_LANGUAGE: "Use game language"
 MAX_TOOLTIP_SIZE: "Max tooltip width"
 MAX_TOOLTIP_SIZE_DESC: "The maximum width of node preview tooltips in pixels."
 USE_GAME_LANGUAGE_DESC: "Always use the language that the currently selected game is in.\nIf this is enabled, the custom language setting below is not used. Note that the translations are incomplete!"
 LANGUAGE: "Language"
 LANGUAGE_DESC: "The custom interface language to use.\nOnly is applied, if the 'Use game language' setting is false."
 SELECT_DIR: "Select $DIR$ directory"
 CHOICE_VALUE_ERROR: "Value $VAL$ is invalid. Resetting it to a default value."
 GAME_DIRS: "Game Installations"
 GAME_DIR_ERROR: "An error occured while loading your $GAME$ installation"
 GAME_DIR_ERROR_MSG: "$GAME$ support has been disabled. If you believe that your installation is valid,\nplease check whether the installation directory was correctly set."
 GAME_DIR: "$GAME$ installation"
 GAME_DIR_DESC: "The $GAME$ installation directory.\n\nNote that this should be the installation directory that contains the game executable and assets.\nNOT the user directory that contains your savegames and mods."
 STORAGE_DIR: "Storage directory"
 STORAGE_DIR_DESC: "The directory where the Pdx-Unlimiter stores all the imported savegames.\nNote that this is completely independet from your savegame directories of your Paradox games!"
 STORAGE_DIR_DIALOG_TITLE: "Confirm storage move"
 STORAGE_DIR_DIALOG_TEXT: "You are trying to move your savegame storage from $FROM$\nto $TO$.\nThis will move all savegame files and may take a while."
 STORAGE_DIR_SAVEGAME_WARNING_TITLE: "Invalid internal storage location"
 STORAGE_DIR_SAVEGAME_WARNING_TEXT: "The directory you selected as the internal storage location of the Pdx-Unlimiter looks like a savegame directory of a game.\nPlease note that the internal storage of the Pdx-Unlimiter is not related to the savegame directories of Paradox games.\n"
 STORAGE_DIR_RESET_TITLE: "Storage directory does not exist"
 STORAGE_DIR_RESET_TEXT: "Storage directory $PATH$ does not exist or is not valid anymore!\nDo you want to reset it to the default directory?"
 STORAGE_DIR_INVALID_TITLE: "Storage directory does not exist"
 STORAGE_DIR_INVALID_TEXT: "Storage directory $PATH$ does not exist or is not valid."
 EU4SE: "Eu4SaveEditor"
 ENABLE_EU4SE: "Enable Eu4SaveEditor"
 ENABLE_EU4SE_DESC: "Specifies whether to enable the Eu4SaveEditor.\n\nIf you enable this, the Eu4SaveEditor will be downloaded and installed next time you start the Pdx-Unlimiter."
 MISC: "Miscellaneous"
 FONT_SIZE: "Font size"
 FONT_SIZE_DESC: "The font size within the app.\n\nIf you have a high display resolution, you can turn this up to increase readability."
 ENABLE_AUTOUPDATE: "Enable auto update"
 ENABLE_AUTOUPDATE_DESC: "Specifies whether to automatically update the Pdx-Unlimiter and its components when launching it."
 CONFIRM_DELETION: "Confirm deletion"
 CONFIRM_DELETION_DESC: "Specifies whether to ask for confirmation when deleting a campaign or savegame."
 START_STEAM: "Start through Steam"
 START_STEAM_DESC: "Specifies whether to start Steam when launching a game through the Pdx-Unlimiter.\n\nIf you disable this, Steam might not register your achievements while playing."
 DELETE_ON_IMPORT: "Delete original after import"
 DELETE_ON_IMPORT_DESC: "Specifies whether to delete savegames after succesfully importing it into the Pdx-Unlimiter storage."
 SKANDERBEG: "Skanderbeg.pm"
 SKANDERBEG_API_KEY: "API key"
 SKANDERBEG_API_KEY_DESC: "Your Skanderbeg.pm API key.\n\nYou can find this by going to the 'API' page on Skanderbeg.pm."
 CONVERTERS: "Paradox Converters"
 CK3_TO_EU4_DIR: "CK3 to EU4 converter"
 CK3_TO_EU4_DIR_DESC: "The path to the CK3ToEU4 converter."
 IRONY_DIR: "Installation location"
 IRONY_DIR_DESC: "The location of your Irony installation."
 LAUNCH_IRONY: "Launch Irony"
 LAUNCH_IRONY_DESC: "Launches the Irony mod manager instead of the Paradox Launcher"
 TIMED_IMPORTS: "Enabled timed imports"
 TIMED_IMPORTS_DESC: "Enables automatically importing the latest savegame after a certain time has passed while playing."
 TIMED_IMPORTS_INTERVAL: "Minutes between imports"
 TIMED_IMPORTS_INTERVAL_DESC: "The interval between automatic imports in minutes."
 THIRD_PARTY_ERROR: "$APP$ support has been disabled.\nIf you believe that the installation is valid,\nplease check whether the installation directory was correctly set."
 PLAY_SOUND_ON_BACKGROUND_IMPORT: "Play sound on background import"
 PLAY_SOUND_ON_BACKGROUND_IMPORT_DESC: "Play a beep sound when importing a savegame while a game is open and the Pdx-Unlimiter is running in the background."
 XBOX_UNAVAILABLE: "This game does not have a Windows Store distribution."
 XBOX_DIST_BUTTON: "Select Windows Store distribution.\nThis only works if you have a Windows Store version of the game installed."
 CLEAR_DIST_BUTTON: "Clear the currently selected game distribution."
 BROWSE_DIST_BUTTON: "Locate the installation directory manually."
 IMPORT_ON_NORMAL_GAME_EXIT: "Import on game exit"
 IMPORT_ON_NORMAL_GAME_EXIT_DESC: "Automatically import the latest savegame when exiting the game normally, i.e. when not using any savescum features."