l_french:
 SETTINGS: "Paramètres"
 INTERFACE: "Interface"
 GENERAL: "Général"
 IMPORTS: "Importations"
 IRONY: "Gestionnaire de mods Irony"
 USE_GAME_LANGUAGE: "Utiliser la langue du jeu "
 MAX_TOOLTIP_SIZE: "Largeur maximale des infobulles"
 MAX_TOOLTIP_SIZE_DESC: "La largeur maximale des infobulles de l'aperçu des nœuds en pixels."
 USE_GAME_LANGUAGE_DESC: "Toujours utiliser la langue du jeu actuellement sélectionné. Si cette option est activée, le paramètre de langue personnalisé ci-dessous n'est pas utilisé."
 LANGUAGE: "Langue "
 LANGUAGE_DESC: "La langue à utiliser pour l'interface. Elle n'est appliquée que si le paramètre "Utiliser la langue du jeu" est faux."
 SELECT_DIR: "Sélectionner l'$DIR$"
 CHOICE_VALUE_ERROR: "La valeur $VAL$ n'est pas valide. Remise à une valeur par défaut."
 GAME_DIRS: "Dossiers d'installation des jeux"
 GAME_DIR_ERROR: "Une erreur s'est produite lors du chargement de votre installation de $GAME$."
 GAME_DIR_ERROR_MSG: "Le support de $GAME$ a été désactivé. Si vous pensez que votre installation est valide, veuillez vérifier si le dossier d'installation a été correctement défini."
 GAME_DIR: "Emplacement de $GAME$ "
 GAME_DIR_DESC: "Le dossier d'installation $GAME$.\n\nNotez qu'il doit s'agir du dossier d'installation qui contient l'exécutable et les ressources du jeu, et NON du dossier utilisateur qui contient vos sauvegardes et vos mods."
 STORAGE_DIR: "Dossier de stockage "
 STORAGE_DIR_DESC: "Le dossier où Pdx-Unlimiter stocke toutes les sauvegardes importées. \nNotez que ce dossier est complètement indépendant des dossiers de sauvegarde de vos jeux Paradox !"
 STORAGE_DIR_DIALOG_TITLE: "Confirmer le changement de dossier de stockage"
 STORAGE_DIR_DIALOG_TEXT: "Vous essayez de déplacer le stockage de vos sauvegardes de $FROM$\nà $TO$.\nCela va déplacer tous les fichiers de sauvegarde et peut prendre un certain temps."
 STORAGE_DIR_SAVEGAME_WARNING_TITLE: "Emplacement de stockage interne invalide"
 STORAGE_DIR_SAVEGAME_WARNING_TEXT: "Le dossier que vous avez sélectionné comme emplacement de stockage interne du Pdx-Unlimiter ressemble à un dossier de sauvegarde d'un jeu.\nVeuillez noter que le stockage interne de Pdx-Unlimiter n'est pas lié aux dossiers de sauvegarde des jeux Paradox.\n"
 STORAGE_DIR_RESET_TITLE: "Le dossier de stockage n'existe pas"
 STORAGE_DIR_RESET_TEXT: "Le dossier de stockage $PATH$ n'existe pas ou n'est plus valide!\nVoulez-vous le réinitialiser au dossier par défaut ?"
 STORAGE_DIR_INVALID_TITLE: "Le dossier de stockage n'existe pas"
 STORAGE_DIR_INVALID_TEXT: "Le dossier de stockage $PATH$ n'existe pas ou n'est pas valide."
 EU4SE: "Eu4SaveEditor"
 ENABLE_EU4SE: "Activer Eu4SaveEditor "
 ENABLE_EU4SE_DESC: "Indique si vous souhaitez activer l'éditeur Eu4SaveEditor. Si vous activez cette option, l'éditeur Eu4SaveEditor sera téléchargé et installé lors du prochain démarrage de Pdx-Unlimiter."
 MISC: "Divers"
 FONT_SIZE: "Taille de la police "
 FONT_SIZE_DESC: "La taille de la police dans l'application.\n\nSi vous avez un écran avec une grande d'une résolution, vous pouvez l'augmenter pour améliorer la lisibilité."
 ENABLE_AUTOUPDATE: "Activer les mises à jour automatiques "
 ENABLE_AUTOUPDATE_DESC: "Indique s'il faut mettre à jour automatiquement le Pdx-Unlimiter et ses dépendences lors de son lancement."
 CONFIRM_DELETION: "Confirmer la suppression "
 CONFIRM_DELETION_DESC: "Indique s'il faut demander une confirmation lors de la suppression d'une campagne ou d'une sauvegarde."
 START_STEAM: "Démarrer avec Steam "
 START_STEAM_DESC: "Indique s'il faut lancer Steam lors du lancement d'un jeu via le Pdx-Unlimiter.\n\nSi vous désactivez cette option, il se peut que Steam n'enregistre pas vos succès pendant le jeu."
 DELETE_ON_IMPORT: "Supprimer après l'import "
 DELETE_ON_IMPORT_DESC: "Indique s'il faut supprimer les sauvegardes après les avoir importées avec succès dans le stockage Pdx-Unlimiter."
 SKANDERBEG: "Skanderbeg.pm"
 SKANDERBEG_API_KEY: "Clé API "
 SKANDERBEG_API_KEY_DESC: "Votre clé API Skanderbeg.pm.\n\nVous pouvez la trouver en vous rendant sur la page "API" de Skanderbeg.pm."
 CONVERTERS: "Convertisseurs Paradox"
 CK3_TO_EU4_DIR: "Convertisseur CK3 vers EU4 "
 CK3_TO_EU4_DIR_DESC: "Le chemin vers le convertisseur CK3ToEU4."
 IRONY_DIR: "Emplacement de l'installation "
 IRONY_DIR_DESC: "Emplacement de l'installation d'Irony."
 LAUNCH_IRONY: "Démarrer Irony "
 LAUNCH_IRONY_DESC: "Lance le gestionnaire de mods Irony au lieu du lanceur Paradox."
 TIMED_IMPORTS: "Activation des importations planifiées "
 TIMED_IMPORTS_DESC: "Permet d'importer automatiquement la dernière sauvegarde après un certain temps de jeu."
 TIMED_IMPORTS_INTERVAL: "Minutes entre les importations "
 TIMED_IMPORTS_INTERVAL_DESC: "L'intervalle entre les importations automatiques en minutes."
 THIRD_PARTY_ERROR: "Le support de $APP$ a été désactivé.\n\nSi vous pensez que l'installation est valide, veuillez vérifier si le dossier d'installation a été correctement défini."
 PLAY_SOUND_ON_BACKGROUND_IMPORT: "Jouer un son lors d'une importation en arrière-plan "
 PLAY_SOUND_ON_BACKGROUND_IMPORT_DESC: "Émettre un bip sonore lors de l'importation d'une sauvegarde alors qu'un jeu est ouvert et que Pdx-Unlimiter fonctionne en arrière-plan."
 XBOX_UNAVAILABLE: "Ce jeu n'a pas de version Windows Store."
 XBOX_DIST_BUTTON: "Sélectionnez la version Windows Store.\nCela ne fonctionne que si vous avez installé une version Windows Store du jeu."
 CLEAR_DIST_BUTTON: "Efface la version de jeu actuellement sélectionnée."
 BROWSE_DIST_BUTTON: "Indiquer manuellement le dossier d'installation."