l_japanese:
 SETTINGS: "設定"
 INTERFACE: "インターフェイス"
 GENERAL: "一般"
 IMPORTS: "読み込み"
 IRONY: "Ironyモッドマネージャー"
 USE_GAME_LANGUAGE: "ゲーム言語を使う"
 MAX_TOOLTIP_SIZE: "ツールチップの最大幅"
 MAX_TOOLTIP_SIZE_DESC: "ノードプレビューツールチップの最大幅をピクセルで指定します。"
 USE_GAME_LANGUAGE_DESC: "常に現在選択されているゲームの言語を使用してください。\nこの設定が有効な場合、以下のカスタム言語設定は使用されません。翻訳が不完全であることに注意してください!"
 LANGUAGE: "言語"
 LANGUAGE_DESC: "使用するカスタムインターフェース言語です。"
 SELECT_DIR: "$DIR$ディレクトリの選択"
 CHOICE_VALUE_ERROR: "値$VAL$は無効です。初期値に戻します。"
 GAME_DIRS: "ゲームのインストール先"
 GAME_DIR_ERROR: "$GAME$のロード中にエラーが発生します。"
 GAME_DIR_ERROR_MSG: "$GAME$サポートは無効になっています。インストールが有効であると思われる場合。\nインストール先が正しく設定されているかをご確認ください。"
 GAME_DIR: "$GAME$のインストール先"
 GAME_DIR_DESC: "$GAME$のインストールディレクトリです。\n\nゲームの実行ファイルとアセットを含むインストールディレクトリである必要があることに注意してください。\nセーブゲームやMODが格納されているユーザーディレクトリではありません。"
 STORAGE_DIR: "ストレージディレクトリ"
 STORAGE_DIR_DESC: "Pdx-Unlimiterが、インポートしたすべてのセーブゲームを保存するディレクトリです。\nこれはパラドックスゲームのセーブゲームディレクトリとは完全に独立していることに注意してください。"
 STORAGE_DIR_DIALOG_TITLE: "ストレージの移動を確認する"
 STORAGE_DIR_DIALOG_TEXT: "セーブゲームストレージを$FROM$から\n$TO$に移動しようとしています。\nすべてのセーブゲームファイルを移動させるため、しばらく時間がかかる場合があります。"
 STORAGE_DIR_SAVEGAME_WARNING_TITLE: "内部ストレージの場所が無効"
 STORAGE_DIR_SAVEGAME_WARNING_TEXT: "Pdx-Unlimiterの内部ストレージの場所として選択されたディレクトリは、ゲームのセーブゲームディレクトリのように見えます。\nPdx-Unlimiterの内部ストレージは、パラドックス社のゲームのセーブゲームディレクトリとは関係ありませんのでご注意ください。\n"
 STORAGE_DIR_RESET_TITLE: "ストレージディレクトリが存在しない"
 STORAGE_DIR_RESET_TEXT: "ストレージディレクトリ$PATH$が存在しないか、または無効になっています。\nデフォルトのディレクトリにリセットしますか？"
 STORAGE_DIR_INVALID_TITLE: "ストレージディレクトリが存在しない"
 STORAGE_DIR_INVALID_TEXT: "ストレージディレクトリ$PATH$が存在しないか、有効ではありません。"
 EU4SE: "Eu4セーブ編集"
 ENABLE_EU4SE: "Eu4セーブ編集を有効化する。"
 ENABLE_EU4SE_DESC: "Eu4セーブ編集を有効にするかどうかを指定します。\n\n有効にすると、次回Pdx-Unlimiterを起動したときにEu4セーブ編集がダウンロードされインストールされます。"
 MISC: "その他"
 FONT_SIZE: "フォントサイズ"
 FONT_SIZE_DESC: "アプリ内のフォントサイズです。\n\nディスプレイの解像度が高い場合は、これを大きくすることで読みやすさを向上させることができます。"
 ENABLE_AUTOUPDATE: "自動更新を有効にする"
 ENABLE_AUTOUPDATE_DESC: "Pdx-Unlimiterとそのコンポーネントを起動時に自動的に更新するかどうかを指定します。"
 CONFIRM_DELETION: "削除の確認"
 CONFIRM_DELETION_DESC: "キャンペーンやセーブゲームを削除するときに、確認を求めるかどうかを指定します。"
 START_STEAM: "Steamで起動"
 START_STEAM_DESC: "Pdx-Unlimiterでゲームを起動する際に、Steamを起動するかどうかを指定します。\n\n無効にした場合、プレイ中にSteamに実績が登録されない場合があります。"
 DELETE_ON_IMPORT: "インポート後、入力元を削除"
 DELETE_ON_IMPORT_DESC: "Pdx-Unlimiterストレージへのインポートに成功した後、savegamesを削除するかどうかを指定します。"
 SKANDERBEG: "スカンデルベク.pm"
 SKANDERBEG_API_KEY: "API キー"
 SKANDERBEG_API_KEY_DESC: "あなたのSkanderbeg.pmのAPIキー。\n\nこれはSkanderbeg.pmの'API'ページで見つけることができます。"
 CONVERTERS: "パラドックスコンバーター"
 CK3_TO_EU4_DIR: "CK3からEU4へ変換"
 CK3_TO_EU4_DIR_DESC: "CK3ToEU4コンバータへのパスです。"
 IRONY_DIR: "インストール場所"
 IRONY_DIR_DESC: "Ironyのインストール先です。"
 LAUNCH_IRONY: "Ironyを起動"
 LAUNCH_IRONY_DESC: "Paradox Launcherの代わりにIrony mod managerを起動するようにする。"
 TIMED_IMPORTS: "時間指定入力を有効にする"
 TIMED_IMPORTS_DESC: "プレイ中に一定時間が経過すると、自動的に最新のセーブゲームをインポートすることができるようになります。"
 TIMED_IMPORTS_INTERVAL: "入力までの分数"
 TIMED_IMPORTS_INTERVAL_DESC: "自動読み込みの間隔を分単位で指定します。"
 THIRD_PARTY_ERROR: "$APP$のサポートは無効になっています。\nインストールが有効であると思われる場合。\nインストール先が正しく設定されているかをご確認ください。"
 PLAY_SOUND_ON_BACKGROUND_IMPORT: "バックグラウンドでの取り込み時に音を鳴らす"
 PLAY_SOUND_ON_BACKGROUND_IMPORT_DESC: "ゲームを開いていてPdx-Unlimiterがバックグラウンドで動作しているときにセーブゲームを取り込むと、ビープ音を鳴らすようにします。"
 XBOX_UNAVAILABLE: "このゲームはWindowsストアでの配信は行っておりません。"
 XBOX_DIST_BUTTON: "Windows ストア配信を選択します。\nWindowsストア版がインストールされている場合のみ有効です。"
 CLEAR_DIST_BUTTON: "現在選択されているゲーム配信を削除します。"
 BROWSE_DIST_BUTTON: "インストール先のディレクトリを手動で探します。"
 IMPORT_ON_NORMAL_GAME_EXIT: "ゲーム終了時を読み込み"
 IMPORT_ON_NORMAL_GAME_EXIT_DESC: "セーブカム機能を使用しない通常のゲーム終了時に、最新のセーブゲームを自動的にインポートするようにします。"
