l_chinese:
 SETTINGS: "设置"
 INTERFACE: "界面"
 GENERAL: "通用"
 IMPORTS: "导入"
 IRONY: "Irony mod manager"
 USE_GAME_LANGUAGE: "使用游戏语言"
 MAX_TOOLTIP_SIZE: "消息框最大宽度"
 MAX_TOOLTIP_SIZE_DESC: "节点预览消息框的最大宽度（像素）。"
 USE_GAME_LANGUAGE_DESC: "始终使用游戏中的语言。\n启用后下方的语言设置将无效。需要注意的是翻译尚未完善！"
 LANGUAGE: "语言"
 LANGUAGE_DESC: "自定义显示语言。\n在勾选「使用游戏语言」后无效。"
 SELECT_DIR: "选择 $DIR$ 目录"
 CHOICE_VALUE_ERROR: "$VAL$ 是无效的值。正在重置回默认值。"
 GAME_DIRS: "游戏路径"
 GAME_DIR_ERROR: "在加载 $GAME$ 安装路径时发生错误"
 GAME_DIR_ERROR_MSG: "$GAME$ 支持已被禁用。如果你确定你已经安装了该游戏，请确保游戏安装路径正确无误。"
 GAME_DIR: "$GAME$"
 GAME_DIR_DESC: "$GAME$ 安装路径\n\n即包含游戏本体及资源文件的路径\n并不是包含游戏存档和模组的用户数据路径"
 STORAGE_DIR: "存储路径"
 STORAGE_DIR_DESC: "此目录用于储存所有导入至 Pdx-Unlimiter 的存档。\n这与你的游戏存档路径没有任何关联！"
 STORAGE_DIR_DIALOG_TITLE: "存储移动确认"
 STORAGE_DIR_DIALOG_TEXT: "你正在尝试将存档存储从 $FROM$\n移动至 $TO$。\n这将移动所有的存档文件并需要耗费一定时间。"
 STORAGE_DIR_SAVEGAME_WARNING_TITLE: "无效的存储路径"
 STORAGE_DIR_SAVEGAME_WARNING_TEXT: "你似乎选择了游戏的存档路径。\n请注意 Pdx-Unlimiter 的存储路径与游戏存档路径没有任何关联！\n"
 STORAGE_DIR_RESET_TITLE: "存储路径不存在"
 STORAGE_DIR_RESET_TEXT: "存储路径 $PATH$ 不存在或不可用。\n重置回默认路径吗？"
 STORAGE_DIR_INVALID_TITLE: "存储路径不存在"
 STORAGE_DIR_INVALID_TEXT: "存储路径 $PATH$ 不存在或不可用。"
 EU4SE: "Eu4SaveEditor"
 ENABLE_EU4SE: "启用 Eu4SaveEditor"
 ENABLE_EU4SE_DESC: "选择是否启用 Eu4SaveEditor.\n\n启用后将会自动在下次启动时下载并安装 Eu4SaveEditor。"
 MISC: "杂项"
 FONT_SIZE: "字体大小"
 FONT_SIZE_DESC: "如果你正在使用高分辨率显示器，你可以适当调高以增加可读性。"
 ENABLE_AUTOUPDATE: "启用自动更新"
 ENABLE_AUTOUPDATE_DESC: "是否在启动时自动更新 Pdx-Unlimiter 及相关组件。"
 CONFIRM_DELETION: "启用删除确认"
 CONFIRM_DELETION_DESC: "是否在删除战役或存档时要求二次确认。"
 START_STEAM: "使用 Steam 启动"
 START_STEAM_DESC: "是否通过 Steam 启动游戏。\n\n禁用后 Steam 可能不会记录你的成就。"
 DELETE_ON_IMPORT: "导入后删除"
 DELETE_ON_IMPORT_DESC: "是否在成功导入存档至 Pdx-Unlimiter 后删除游戏内存档。"
 SKANDERBEG: "Skanderbeg.pm"
 SKANDERBEG_API_KEY: "API 密钥"
 SKANDERBEG_API_KEY_DESC: "你的 Skanderbeg.pm API 密钥。\n\n密钥可以在 Skanderbeg.pm 的 API 页面找到。"
 CONVERTERS: "Paradox 转换器"
 CK3_TO_EU4_DIR: "CK3 to EU4 converter"
 CK3_TO_EU4_DIR_DESC: "CK3ToEU4 converter 的路径。"
 IRONY_DIR: "安装路径"
 IRONY_DIR_DESC: "Irony 的安装路径。"
 LAUNCH_IRONY: "启动 Irony"
 LAUNCH_IRONY_DESC: "使用 Irony 取代 Paradox 官方启动器。"
 TIMED_IMPORTS: "启用定时导入"
 TIMED_IMPORTS_DESC: "在游玩时定时导入最新的存档。"
 TIMED_IMPORTS_INTERVAL: "导入间隔（分钟）"
 TIMED_IMPORTS_INTERVAL_DESC: "导入间隔（分钟）。"
 THIRD_PARTY_ERROR: "$APP$ 支持已被禁用。\n如果你确定你已经安装了该软件，请确保游戏安装路径正确无误。"
 PLAY_SOUND_ON_BACKGROUND_IMPORT: "背景提示音"
 PLAY_SOUND_ON_BACKGROUND_IMPORT_DESC: "在后台自动导入存档时播放提示音。"
 XBOX_UNAVAILABLE: "此游戏并不在微软商店发行。"
 XBOX_DIST_BUTTON: "选择微软商店版本。\n仅在你已安装微软商店版本的游戏时适用。"
 CLEAR_DIST_BUTTON: "清除当前选中的游戏发行版信息。"
 BROWSE_DIST_BUTTON: "手动选择游戏安装路径。"